name: 論文のIssue作成

on:
  push:
    branches:
      - main  # または適切なブランチ名
    paths:
      - '.github/workflows/issue_creator.yml'
      - 'papers.json'
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2

    - name: Pythonのセットアップ
      uses: actions/setup-python@v4
      # ↑ v2->v4
      with:
        python-version: '3.12'
        # ↑ Python 3.12 に固定

    - name: Check Python version  
      run: |
        python --version
        which python

    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt

    - name: Issue作成スクリプトの実行
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YOUR_PERSONAL_ACCESS_TOKEN_YUKIHIKO: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN_YUKIHIKO }}
      run: python .github/scripts/issue_creator.py

# ---------------
# debug code
#
# act workflow_dispatch -W .github/workflows/issue_creator.yml --env-file .env --secret-file .env -v
